# Generated by Django 4.0.5 on 2022-07-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='is_student',
            new_name='is_doctor',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='is_teacher',
            new_name='is_user',
        ),
        migrations.AddField(
            model_name='login',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='age',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='contact_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='gender',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
